name: lession 1
on:
#  push:
#    branchs:
#      - master
  workflow_dispatch:
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress
      - name: Copy env
        run: cp .env.example .env
      - name: Generate app key
        run: php artisan key:generate
      - name: List files before checkout
        run: ls -la
      - name: Run tests
        run: php artisan test
      - name: check os
        run: uname -a
      - name: check php version
        run: php -v
      - name: check composer version
        run: composer -V