name: lession 1
on:
  push:
    branchs:
      - master
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: check os
        run: uname -a
      - name: check php version
        run: php -v
      - name: check composer version
        run: composer -V