name: lession 1
on:
  push:
    branchs:
      - master
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: List files before checkout
        run: ls -la
      - name: check os
        run: uname -a
      - name: check php version
        run: php -v
      - name: check composer version
        run: composer -V